<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Restaurante;

class RestauranteSeeder extends Seeder
{
    public function run(): void
    {
        // Restaurante::create([
        //     'nombre' => 'Al-Andalus',
        //     'direccion' => 'Calle Lavapiés, 12',
        //     'ciudad' => 'Madrid',
        //     'latitud' => 40.40800000,
        //     'longitud' => -3.70200000,
        //     'tipo_cocina' => 'Marroquí',
        //     'descripcion' => 'Especialidades halal de Marruecos, couscous, tajines y dulces árabes.',
        //     'telefono' => '+34 600 123 456',
        //     'foto_principal' => 'https://www.aramultimedia.com/lib/timThumb/timThumb.php?src=/upload/images/Articles-Externs/Javi-Navarro/restaurante-arabe.jpg&w=800&zc=2&a=c',
        //     'administrador_id' => '12345678A', // este DNI debe existir en la tabla `usuarios`
        // ]);
        // Restaurante::create([
        //     'nombre' => 'Sabores del Desierto',
        //     'direccion' => 'Calle Embajadores, 45',
        //     'ciudad' => 'Madrid',
        //     'latitud' => 40.40420000,
        //     'longitud' => -3.70350000,
        //     'tipo_cocina' => 'Túnez',
        //     'descripcion' => 'Restaurante familiar con platos tradicionales tunecinos halal como brik, couscous y harissa.',
        //     'telefono' => '+34 611 234 567',
        //     'foto_principal' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/dd/1f/73/p-20180726-214945-largejpg.jpg?w=900&h=-1&s=1',
        //     'administrador_id' => '12345678A',
        // ]);
        
        // Restaurante::create([
        //     'nombre' => 'El Oasis Halal',
        //     'direccion' => 'Calle Atocha, 89',
        //     'ciudad' => 'Madrid',
        //     'latitud' => 40.41000000,
        //     'longitud' => -3.69500000,
        //     'tipo_cocina' => 'Libanesa',
        //     'descripcion' => 'Experiencia auténtica de la cocina libanesa con ingredientes 100% halal y ambiente acogedor.',
        //     'telefono' => '+34 622 987 654',
        //     'foto_principal' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/27/b6/44/chez-michel-el-libanes.jpg?w=900&h=500&s=1',
        //     'administrador_id' => '12345678A',
        // ]);
                Restaurante::insert([
            [
                'nombre' => 'El Rincón Halal',
                'direccion' => 'Calle Atocha, 123',
                'ciudad' => 'Madrid',
                'latitud' => 40.4102,
                'longitud' => -3.6947,
                'tipo_cocina' => 'Marroquí',
                'descripcion' => 'Especialidades en cuscús, tajines y repostería árabe.',
                'telefono' => '+34 600 100 001',
                'foto_principal' => 'https://source.unsplash.com/featured/?moroccan-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Sabores de Lavapiés',
                'direccion' => 'Calle Embajadores, 45',
                'ciudad' => 'Madrid',
                'latitud' => 40.4080,
                'longitud' => -3.7020,
                'tipo_cocina' => 'Paquistaní',
                'descripcion' => 'Comida tradicional pakistaní con certificación halal.',
                'telefono' => '+34 600 100 002',
                'foto_principal' => 'https://source.unsplash.com/featured/?pakistani-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Tandoori Vallecas',
                'direccion' => 'Avenida de la Albufera, 150',
                'ciudad' => 'Madrid',
                'latitud' => 40.3911,
                'longitud' => -3.6585,
                'tipo_cocina' => 'India Halal',
                'descripcion' => 'Platos tandoori, curry y biryanis con productos certificados.',
                'telefono' => '+34 600 100 003',
                'foto_principal' => 'https://source.unsplash.com/featured/?indian-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Kebab Arganzuela',
                'direccion' => 'Paseo de las Delicias, 120',
                'ciudad' => 'Madrid',
                'latitud' => 40.3945,
                'longitud' => -3.6960,
                'tipo_cocina' => 'Turca',
                'descripcion' => 'Doner kebab, dürum y platos caseros turcos halal.',
                'telefono' => '+34 600 100 004',
                'foto_principal' => 'https://source.unsplash.com/featured/?turkish-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Alhambra Latina',
                'direccion' => 'Calle Bravo Murillo, 220',
                'ciudad' => 'Madrid',
                'latitud' => 40.4543,
                'longitud' => -3.7031,
                'tipo_cocina' => 'Fusión Árabe-Latina',
                'descripcion' => 'Comida halal con influencias árabes y latinas.',
                'telefono' => '+34 600 100 005',
                'foto_principal' => 'https://source.unsplash.com/featured/?fusion-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Damasco Center',
                'direccion' => 'Calle de Toledo, 85',
                'ciudad' => 'Madrid',
                'latitud' => 40.4079,
                'longitud' => -3.7112,
                'tipo_cocina' => 'Siria',
                'descripcion' => 'Auténtica cocina siria: shawarmas, hummus y falafel.',
                'telefono' => '+34 600 100 006',
                'foto_principal' => 'https://source.unsplash.com/featured/?syrian-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Medina Gourmet',
                'direccion' => 'Calle General Ricardos, 210',
                'ciudad' => 'Madrid',
                'latitud' => 40.3845,
                'longitud' => -3.7220,
                'tipo_cocina' => 'Marroquí Premium',
                'descripcion' => 'Restaurante gourmet con menú degustación halal.',
                'telefono' => '+34 600 100 007',
                'foto_principal' => 'https://source.unsplash.com/featured/?gourmet-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Sabor Libanés Retiro',
                'direccion' => 'Calle de Ibiza, 15',
                'ciudad' => 'Madrid',
                'latitud' => 40.4160,
                'longitud' => -3.6765,
                'tipo_cocina' => 'Libanesa',
                'descripcion' => 'Platos frescos y tradicionales del Líbano, halal certificado.',
                'telefono' => '+34 600 100 008',
                'foto_principal' => 'https://source.unsplash.com/featured/?lebanese-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Andalusí Chamartín',
                'direccion' => 'Calle Príncipe de Vergara, 290',
                'ciudad' => 'Madrid',
                'latitud' => 40.4622,
                'longitud' => -3.6760,
                'tipo_cocina' => 'Andalusí Halal',
                'descripcion' => 'Comida típica andalusí adaptada a la tradición halal.',
                'telefono' => '+34 600 100 009',
                'foto_principal' => 'https://source.unsplash.com/featured/?andalusian-food',
                'administrador_id' => '12345678A',
            ],
            [
                'nombre' => 'Halal Fusion Centro',
                'direccion' => 'Gran Vía, 80',
                'ciudad' => 'Madrid',
                'latitud' => 40.4220,
                'longitud' => -3.7060,
                'tipo_cocina' => 'Fusión Asiática Halal',
                'descripcion' => 'Fusión de sabores asiáticos con cocina halal certificada.',
                'telefono' => '+34 600 100 010',
                'foto_principal' => 'https://source.unsplash.com/featured/?asian-food',
                'administrador_id' => '12345678A',
            ],
        ]);
    }
}
